name: 'PHP Tests'
description: 'Run PHP test frameworks (e.g., PHPStan and PHPUnit).'
inputs:
  php-version:
    description: 'The PHP version to use.'
    default: 'latest'
    required: false
  php-vendor-dir:
    description: 'The directory where PHP dependencies are installed.'
    default: './vendor'
    required: false
  # PHPStan options
  phpstan-enable:
    description: 'Whether to enable PHPStan.'
    default: 'true'
    required: false
  phpstan-config:
    description: 'The location of the PHPStan configuration file.'
    default: 'phpstan.neon'
    required: false
  phpstan-memory-limit:
    description: 'The memory limit for PHPStan.'
    default: '1G'
    required: false      
  phpstan-php-version:
    description: 'The PHP version to use with PHPStan.'
    default: 'latest'
    required: false
  # PHPUnit options 
  phpunit-enable:
    description: 'Whether to enable PHPUnit.'
    default: 'true'
    required: false
  phpunit-config-file:
    description: 'The location of the PHPUnit configuration file.'
    default: 'phpunit.xml.dist'
    required: false
  # Pest options
  pest-enable:
    description: 'Whether to enable Pest.'
    default: 'false'
    required: false
  pest-config-file:
    description: 'The location of the Pest/PHPUnit configuration file.'
    default: 'phpunit.xml.dist'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'PHPStan'
      if: ${{ inputs.phpstan-enable == 'true' && inputs.php-version == inputs.phpstan-php-version }}
      shell: bash
      run: ${{ inputs.php-vendor-dir }}/bin/phpstan analyse --configuration ${{ inputs.phpstan-config }} --memory-limit=${{ inputs.phpstan-memory-limit }}

    - name: 'PHPUnit'
      if: ${{ inputs.phpunit-enable == 'true' && inputs.pest-enable != 'true' }}
      shell: bash
      run: ${{ inputs.php-vendor-dir }}/bin/phpunit --configuration ${{ inputs.phpunit-config-file }}

    - name: 'Pest'
      if: ${{ inputs.pest-enable == 'true' }}
      shell: bash
      run: ${{ inputs.php-vendor-dir }}/bin/pest --configuration ${{ inputs.pest-config-file }}
