name: PHP Build

on: 
  workflow_call:
    inputs:
      cache-deps:
        description: ''
        default: true
        required: false
        type: boolean
      upload-artifact:
        description: ''
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v6
        with:
          command: validate

      - name: 'Cache Composer Dependencies'
        if: ${{ inputs.cache-deps }}
        uses: actions/cache@v3
        with: 
          


      

