name: Spellcheck

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Directory where cspell.json is located'
        required: false
        type: string
      incremental-only:
        description: 'Limit files checked to those in pull request/push'
        default: true
        required: false
        type: boolean
      root-path:
        description: 'Directory in tree to begin spell check'
        required: false
        type: string
      strict:
        description: 'Spelling issues should cause failure'
        default: true
        required: false
        type: boolean
   
jobs:
  spellcheck:
    name: Perform Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          config: ${{ inputs.config-path }}
          root: ${{ inputs.root-path }}
          strict: ${{ inputs.strict }}
          incremental_files_only: ${{ inputs.incremental-only }}